### PR TITLE
fix: typo in playbook run command

### PR DESCRIPTION
**Pull request by jackhodgkiss**

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
@jackhodgkiss could you target this at Yoga first then we'll merge it up

**Comment by jackhodgkiss** [comment]
> @jackhodgkiss could you target this at Yoga first then we'll merge it up

Any reason why? Most PRs open are against `stackhpc/2023.1`

**Comment by Alex-Welsh** [comment]
> > @jackhodgkiss could you target this at Yoga first then we'll merge it up
> 
> Any reason why? Most PRs open are against `stackhpc/2023.1`

In general new features go to antelope, fixes go to yoga

**Comment by priteau** [comment]
You don't need to close the pull request, you can force push and target `stackhpc/yoga` instead.

**Pull request closed without merging**
