### PR TITLE
Enable SELinux in permissive mode in overcloud host images

### PR DESCRIPTION
**Pull request by markgoddard**
This matches our current defaults.

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Have you tried building the images?

**Comment by Alex-Welsh** [comment]
> Have you tried building the images?

Having a go [here](https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/10704184708/job/29676523558)

**Review by Alex-Welsh — APPROVED** [review]
Build didn't work but that's not really any reason to hold up this change

**Comment by markgoddard** [comment]
Sorry, should have been draft. This requires an updated RL9 host image due to the ci-aio SELinux config change.

**Pull request merged**
