### PR TITLE
Bump seed Pulp to version 3.43.1

### PR DESCRIPTION
**Pull request by m-bull**
Ark is now running Pulp version 3.43.2, so it seems reasonable to keep client Pulps in sync as much as possible.

Pulp-in-one version 3.43.1 has already been deployed/used successfully on a new deployment, but further testing is required to ensure an upgrade of a long-running Pulp is successful.

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Tested by @technowhizz, upgraded from 3.21.

**Review by Alex-Welsh — APPROVED** [review]

**Review by MaxBed4d — APPROVED** [review]
As long as it's been thoroughly tested 👀 👀, it looks good to me.

**Comment by technowhizz** [comment]
> As long as it's been thoroughly tested 👀 👀, it looks good to me.

Is anyone and everyone reviewing now @MaxBed4d 😉

**Comment by technowhizz** [comment]
Can confirm. Does work!

**Review by technowhizz — APPROVED** [review]

**Comment by MaxBed4d** [comment]
> > As long as it's been thoroughly tested 👀 👀, it looks good to me.
> 
> Is anyone and everyone reviewing now @MaxBed4d 😉

Apparently, as they're seemingly letting anyone and everyone test systems now @technowhizz 😉

**Review by markgoddard — APPROVED** [review]
Another review

**Pull request merged**
