### PR TITLE
Bump Rocky 9 snapshots

### PR DESCRIPTION
**Pull request by jovial**
This brings in the CPU vulnerability fixes for:

- Zenbleed
- Downfall

### CODE REVIEW

**Review by mnasiadka — DISMISSED** [review]

**Comment by mnasiadka** [comment]
Just thinking if we shouldn't have a reno?

**Comment by jovial** [comment]
> Just thinking if we shouldn't have a reno?

Good point. forgot to push that :facepalm:

**Review by mnasiadka — DISMISSED** [review]

**Comment by jovial** [comment]
Kernel still not patched to fully mitigate vulnerability (5.14.0-284.30.1.el9_2.x86_64) :(

**Review by cityofships — DISMISSED** [review]

**Comment by cityofships** [comment]
> Kernel still not patched to fully mitigate vulnerability (5.14.0-284.30.1.el9_2.x86_64) :(

Can bump again once updated version is released

**Comment by jovial** [comment]
> > Kernel still not patched to fully mitigate vulnerability (5.14.0-284.30.1.el9_2.x86_64) :(
> 
> Can bump again once updated version is released

Sounds good. I'll remove inception from the release note.

**Review by cityofships — APPROVED** [review]

**Pull request merged**
