### PR TITLE
Bump magnum-capi-helm version to latest

### PR DESCRIPTION
**Pull request by sd109**

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Is this something that only needs to happen in antelope or is it worth doing in Yoga & Zed as well?

**Comment by Alex-Welsh** [comment]
Also, probably worth rebuilding the container and adding the tags to this PR (along with a release note)

**Comment by mnasiadka** [comment]
I don't think we're planning to use CAPI in Yoga (at least I'm not aware of it) - so Antelope is fine.

**Comment by scrungus** [comment]
@mnasiadka  > I don't think we're planning to use CAPI in Yoga (at least I'm not aware of it) - so Antelope is fine.

We'll be wanting to use it at ECMWF, so I think we'd need to backport to yoga

**Comment by markgoddard** [comment]
pep8 failed:

> etc/kayobe/kolla-image-tags.yml
>  20:54     error    no new line character at the end of file  (new-line-at-end-of-file)

Seems a bit harsh to me :)

I'm happy to merge here first then backport to yoga.

**Review by Alex-Welsh — COMMENTED** [review]
nit: missing eof newlines on `kolla-image-tags.yml` and the release note
otherwise LGTM as long as those new images are tested.

**Comment by markgoddard** [comment]
I'm going to merge the yoga change through to zed + antelope, and I'll pick up the tags from this PR for antelope.

**Comment by markgoddard** [comment]
2023.1: https://github.com/stackhpc/stackhpc-kayobe-config/pull/969/
zed: https://github.com/stackhpc/stackhpc-kayobe-config/pull/967

**Pull request closed without merging**
