### PR TITLE
Use intermediate var for Rocky Powertools repo

### PR DESCRIPTION
**Pull request by m-bull**

### CODE REVIEW

**Comment by jovial** [comment]
Think we need this in wallaby too

**Review by priteau — APPROVED** [review]

**Comment by m-bull** [comment]
Should we abandon this in favour of https://github.com/stackhpc/stackhpc-kayobe-config/pull/273 @jovial ?

**Comment by bbezak** [comment]
> Should we abandon this in favour of #273 @jovial ?
looks like a good idea. #273 is for wallaby though, so we would need to sync it to yoga as well

**Comment by markgoddard** [comment]
> > Should we abandon this in favour of #273 @jovial ?
> > looks like a good idea. #273 is for wallaby though, so we would need to sync it to yoga as well

https://github.com/stackhpc/stackhpc-kayobe-config/pull/277
https://github.com/stackhpc/stackhpc-kayobe-config/pull/278

**Comment by m-bull** [comment]
Thanks @markgoddard

**Pull request closed without merging**
