### PR TITLE
zed: yoga merge

### PR DESCRIPTION
**Pull request by markgoddard**
- Update smartmon-tools.yml
- Fix permissions on reset-bls-entries playbook
- CI: Add retries to TF apply in aio job
- CI: Trim down package dependencies
- Correct OpenSearch migration instructions
- Bump docker build and push action to v5
- Bump stackhpc.kayobe_workflows to version 1.0.3
- Revert "Don't verify Apt repo CA initially when using HTTPS in container build"
- Revert "Add package repository credentials to container image build"
- Add Ansible Galaxy roles and collections to .gitignore
- Update etc/kayobe/ansible/smartmon-tools.yml
- Add a playbook to deploy an authenticating Pulp proxy
- Use authenticating Pulp proxy during container image builds
- CI: Avoid hitting Dockerhub rate limits

### CODE REVIEW

**Comment by markgoddard** [comment]
Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888780624

**Comment by markgoddard** [comment]
> Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888780624

Trying again... https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7889078128

**Review by Alex-Welsh — APPROVED** [review]
LGTM as long as image builds & AIOs pass

**Comment by markgoddard** [comment]
> > Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888780624
> 
> Trying again... https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7889078128

Passed

**Comment by markgoddard** [comment]
Upgrade job failed due to yoga net_ip issue, being fixed upstream

**Review by Alex-Welsh — APPROVED** [review]
Still wonder what happened to that `cat` line

**Pull request merged**
