### PR TITLE
Multinode env

### PR DESCRIPTION
**Pull request by jackhodgkiss**
Move wallaby multinode environment into `stackhpc/wallaby` in order to centralise efforts as opposed to it being its own branch.

### CODE REVIEW

**Review by markgoddard — CHANGES_REQUESTED** [review]
We can't do this because it would bring features from xena+ that we don't want in wallaby. I was suggesting we merge the other way

**Comment by jackhodgkiss** [comment]
> We can't do this because it would bring features from xena+ that we don't want in wallaby. I was suggesting we merge the other way

Sorry the misunderstanding. However this branch is based off of stackhpc/wallaby so where would the xena features originate from?

**Comment by markgoddard** [comment]
> > We can't do this because it would bring features from xena+ that we don't want in wallaby. I was suggesting we merge the other way
> 
> Sorry the misunderstanding. However this branch is based off of stackhpc/wallaby so where would the xena features originate from?

We backported some things into multinode-env - LVM, cephadm, etc.

**Comment by markgoddard** [comment]
can this be closed?

**Pull request closed without merging**
