### PR TITLE
Bump kolla tags for Bifrost

### PR DESCRIPTION
**Pull request by assumptionsandg**

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
looks like you need to update your stackhpc/zed checkout and rebase this change

**Comment by markgoddard** [comment]
Needs some explanation of why we need new images.

**Comment by Alex-Welsh** [comment]
Seed images weren't built when the rest were since stackhpc/zed is missing 358b30695cc884c5520ee26ac885776958eb0462, so it's a continuation of that. I rebuilt them this afternoon to get the zed AUFN running.

**Comment by markgoddard** [comment]
Ok, let's get this rebased and merged.

**Review by markgoddard — APPROVED** [review]

**Pull request merged**
