### PR TITLE
2023.1: zed merge

### PR DESCRIPTION
**Pull request by markgoddard**
- Update smartmon-tools.yml
- Fix permissions on reset-bls-entries playbook
- CI: Fix check container image tags job for Ark
- CI: Add retries to TF apply in aio job
- CI: Trim down package dependencies
- Correct OpenSearch migration instructions
- Bump docker build and push action to v5
- CI: Conditional container tag check job
- Bump stackhpc.kayobe_workflows to version 1.0.3
- Revert "Don't verify Apt repo CA initially when using HTTPS in container build"
- Revert "Add package repository credentials to container image build"
- Add Ansible Galaxy roles and collections to .gitignore
- Update etc/kayobe/ansible/smartmon-tools.yml
- Add a playbook to deploy an authenticating Pulp proxy
- Use authenticating Pulp proxy during container image builds
- CI: Avoid hitting Dockerhub rate limits

### CODE REVIEW

**Comment by markgoddard** [comment]
Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888781930

**Comment by markgoddard** [comment]
> Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888781930

Trying again... https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7889077040

**Comment by markgoddard** [comment]
> > Testing container image build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7888781930
> 
> Trying again... https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7889077040

Passed

**Review by Alex-Welsh — APPROVED** [review]
LGTM as long as CI passes

**Pull request merged**
