### PR TITLE
Switch to github hosted runners for host image promote

### PR DESCRIPTION
**Pull request by jovial**
So we can promote images now that SMS lab is down.

### CODE REVIEW

**Comment by jovial** [comment]
Failing with:
```
Run BRANCH=$(awk -F'=' '/defaultbranch/ {print $2}' .gitreview)
awk: fatal: cannot open file `.gitreview' for reading: No such file or directory
Error: Process completed with exit code 2.
```
investigating...

**Comment by markgoddard** [comment]
> Failing with:
> 
> ```
> Run BRANCH=$(awk -F'=' '/defaultbranch/ {print $2}' .gitreview)
> awk: fatal: cannot open file `.gitreview' for reading: No such file or directory
> Error: Process completed with exit code 2.
> ```
> 
> investigating...

It's because SKC is checked out at src/kayobe-config. Looks like we might have been relying on a previous run's checkout, which could have contained anything...

**Comment by jovial** [comment]
Thanks, seems to do the business: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7814044183/job/21314453693

**Review by cityofships — DISMISSED** [review]

**Comment by jovial** [comment]
I've rebased this on yoga (as requested by @markgoddard)

**Review by cityofships — APPROVED** [review]

**Review by markgoddard — APPROVED** [review]

**Pull request merged**
