### PR TITLE
rebuild opensearch images

### PR DESCRIPTION
**Pull request by bbezak**
preparation for https://review.opendev.org/c/openstack/kolla-ansible/+/884376

build with:
https://review.opendev.org/c/openstack/kolla/+/883716
https://github.com/stackhpc/kolla/commit/23e0819d688362ce0b6c564d469f57ea9cbe2731

build: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/6072058437
promote: https://github.com/stackhpc/stackhpc-release-train/actions/runs/6094062526

### CODE REVIEW

**Comment by mnasiadka** [comment]
Should we add opensearch repo to Ark?

**Comment by Alex-Welsh** [comment]
> Should we add opensearch repo to Ark?

It's already there https://github.com/stackhpc/stackhpc-release-train/blob/e3eff5b0be002b0499bab8cdbb63e52603071b78/ansible/inventory/group_vars/all/package-repos#L638

**Comment by mnasiadka** [comment]
> > Should we add opensearch repo to Ark?
> 
> It's already there https://github.com/stackhpc/stackhpc-release-train/blob/e3eff5b0be002b0499bab8cdbb63e52603071b78/ansible/inventory/group_vars/all/package-repos#L638

But we also need the template overrides and repo versions in SKC stackhpc/yoga, right?

**Comment by Alex-Welsh** [comment]
> > > Should we add opensearch repo to Ark?
> > 
> > 
> > It's already there https://github.com/stackhpc/stackhpc-release-train/blob/e3eff5b0be002b0499bab8cdbb63e52603071b78/ansible/inventory/group_vars/all/package-repos#L638
> 
> But we also need the template overrides and repo versions in SKC stackhpc/yoga, right?

Yes, they will need to be added to places like `pulp.yml`,`pulp-repo-versions.yml`, and `kolla.yml`to actually use them

**Review by Alex-Welsh — COMMENTED** [review]
You can rm line 61: `opensearch_tag: "{% raw %}{{ kayobe_image_tags['opensearch'][kolla_base_distro] | default(openstack_tag) }}{% endraw %}"` no longer necessary now the tag isn't in the `kayobe_image_tags` dict

**Comment by bbezak** [comment]
> You can rm line 61: `opensearch_tag: "{% raw %}{{ kayobe_image_tags['opensearch'][kolla_base_distro] | default(openstack_tag) }}{% endraw %}"` no longer necessary now the tag isn't in the `kayobe_image_tags` dict

done, thx

**Review by jovial — APPROVED** [review]
LGTM. Hoping to rebase my change on this one, so keen to get it merged.

**Comment by bbezak** [comment]
> LGTM. Hoping to rebase my change on this one, so keen to get it merged.

however I'm not sure if the tags in current versions are acceptable - as this build used upstream opensearch repos (not ark ones)

**Comment by markgoddard** [comment]
> > LGTM. Hoping to rebase my change on this one, so keen to get it merged.
> 
> however I'm not sure if the tags in current versions are acceptable - as this build used upstream opensearch repos (not ark ones)

Let's go with upstream repos for now.

**Review by markgoddard — APPROVED** [review]

**Comment by bbezak** [comment]
when this merges, we need to also revert revert https://github.com/stackhpc/kolla-ansible/pull/427

**Pull request merged**
