### PR TITLE
Disable ironic prometheus exporter deploy and sync

### PR DESCRIPTION
**Pull request by grzegorzkoper**
More info: https://bugs.launchpad.net/kolla-ansible/+bug/2062401

### CODE REVIEW

**Review by markgoddard — DISMISSED** [review]
Release note?

Also the bug says it's fixed.

**Comment by grzegorzkoper** [comment]
@mnasiadka Pointed out that the bug is only partially fixed.
This fix: https://review.opendev.org/c/openstack/kolla-ansible/+/919513 only relates to the bug, not closes it.

Until thats done, we should disable the exporter.

**Comment by mnasiadka** [comment]
> Release note?
> 
> Also the bug says it's fixed.

It's launchpad UI bug, there's only a committed related-bug fix, it's not a final fix - see the attached patches.

**Comment by markgoddard** [comment]
> > Release note?
> > Also the bug says it's fixed.
> 
> It's launchpad UI bug, there's only a committed related-bug fix, it's not a final fix - see the attached patches.

Ok. Marked the bug as in progress.

**Comment by markgoddard** [comment]
> Release note?
> 
> Also the bug says it's fixed.

Still release note...

**Comment by MoteHue** [comment]
This tripped me up too, so I've taken the liberty of adding the reno. Can we get this merged before any more upgrades start? :)

**Review by mnasiadka — APPROVED** [review]

**Pull request merged**
