### PR TITLE
Apply centos build customisations on rocky also

### PR DESCRIPTION
**Pull request by mnasiadka**

### CODE REVIEW

**Comment by priteau** [comment]
What about also renaming the variable to `kolla_build_customizations_redhat`?

**Comment by Alex-Welsh** [comment]
> What about also renaming the variable to `kolla_build_customizations_redhat`?

`kolla_build_customizations_rhel` would probably match the variable naming in the rest of the file best

**Comment by mnasiadka** [comment]
> > What about also renaming the variable to `kolla_build_customizations_redhat`?
> 
> `kolla_build_customizations_rhel` would probably match the variable naming in the rest of the file best

I would go for kolla_build_customizations_rpm or _el - so which one?

**Comment by priteau** [comment]
> > > What about also renaming the variable to `kolla_build_customizations_redhat`?
> > 
> > 
> > `kolla_build_customizations_rhel` would probably match the variable naming in the rest of the file best
> 
> I would go for kolla_build_customizations_rpm or _el - so which one?

`rpm` would make sense if the other variable was `deb` instead of `ubuntu`. We use a mix of `rhel` and `el`, I slightly prefer the former but feel free to pick `el` if you prefer.

**Review by priteau — APPROVED** [review]

**Pull request merged**
