### PR TITLE
docs: fix link to release train page

### PR DESCRIPTION
**Pull request by priteau**

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
The change looks good, but could you target it at `stackhpc/2023.1`?

**Comment by priteau** [comment]
> The change looks good, but could you target it at `stackhpc/2023.1`?

It was [initially committed](https://github.com/stackhpc/stackhpc-kayobe-config/pull/1125) to `stackhpc/zed` and made it to `stackhpc/2023.1` via a merge, but not to `stackhpc/2024.1`, I don't know why.

**Comment by Alex-Welsh** [comment]
> > The change looks good, but could you target it at `stackhpc/2023.1`?
> 
> It was [initially committed](https://github.com/stackhpc/stackhpc-kayobe-config/pull/1125) to `stackhpc/zed` and made it to `stackhpc/2023.1` via a merge, but not to `stackhpc/2024.1`, I don't know why.

I had assumed it wasn't because the 2023.1 version of the docs links to https://stackhpc-kayobe-config.readthedocs.io/en/stackhpc-2023.1/configuration/release-train which doesn't work, though you're right that the change is there.

**Comment by Alex-Welsh** [comment]
> > > The change looks good, but could you target it at `stackhpc/2023.1`?
> > 
> > 
> > It was [initially committed](https://github.com/stackhpc/stackhpc-kayobe-config/pull/1125) to `stackhpc/zed` and made it to `stackhpc/2023.1` via a merge, but not to `stackhpc/2024.1`, I don't know why.
> 
> I had assumed it wasn't because the 2023.1 version of the docs links to https://stackhpc-kayobe-config.readthedocs.io/en/stackhpc-2023.1/configuration/release-train which doesn't work, though you're right that the change is there.

I think the true fix should be to use a tag and link to that, the advantage there being that we can then rename the page and the link persists

For example:
tag: https://github.com/stackhpc/stackhpc-kayobe-config/blob/stackhpc/2024.1/doc/source/configuration/host-images.rst?plain=1#L1
link: https://github.com/stackhpc/stackhpc-kayobe-config/blob/stackhpc/2024.1/doc/source/configuration/lvm.rst?plain=1#L31

**Comment by priteau** [comment]
> > > The change looks good, but could you target it at `stackhpc/2023.1`?
> > 
> > 
> > It was [initially committed](https://github.com/stackhpc/stackhpc-kayobe-config/pull/1125) to `stackhpc/zed` and made it to `stackhpc/2023.1` via a merge, but not to `stackhpc/2024.1`, I don't know why.
> 
> I had assumed it wasn't because the 2023.1 version of the docs links to https://stackhpc-kayobe-config.readthedocs.io/en/stackhpc-2023.1/configuration/release-train which doesn't work, though you're right that the change is there.

Good catch, it is missing the `.html` extension.

**Review by seunghun1ee — DISMISSED** [review]

**Comment by priteau** [comment]
> > > > The change looks good, but could you target it at `stackhpc/2023.1`?
> > > 
> > > 
> > > It was [initially committed](https://github.com/stackhpc/stackhpc-kayobe-config/pull/1125) to `stackhpc/zed` and made it to `stackhpc/2023.1` via a merge, but not to `stackhpc/2024.1`, I don't know why.
> > 
> > 
> > I had assumed it wasn't because the 2023.1 version of the docs links to https://stackhpc-kayobe-config.readthedocs.io/en/stackhpc-2023.1/configuration/release-train which doesn't work, though you're right that the change is there.
> 
> I think the true fix should be to use a tag and link to that, the advantage there being that we can then rename the page and the link persists
> 
> For example: tag: https://github.com/stackhpc/stackhpc-kayobe-config/blob/stackhpc/2024.1/doc/source/configuration/host-images.rst?plain=1#L1 link: https://github.com/stackhpc/stackhpc-kayobe-config/blob/stackhpc/2024.1/doc/source/configuration/lvm.rst?plain=1#L31

Good suggestion, thanks. I updated the change and targeted stackhpc/zed instead.

**Review by Alex-Welsh — APPROVED** [review]

**Pull request merged**
