### PR TITLE
[2023.1] Fix eswitchd and neutron_mlnx_agent not using our fork

### PR DESCRIPTION
**Pull request by jovial**
The neutron_mlnx_agent based containers are not using the neutron plugins, so we need to customize the pip package directly.

### CODE REVIEW

**Comment by jovial** [comment]
Building here: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/11290127929

**Comment by jovial** [comment]
Seems to work:
```
()[neutron@4aa917cba88e /]$ /var/lib/kolla/venv/bin/pip freeze | grep mlnx
networking-mlnx @ git+https://github.com/stackhpc/networking-mlnx@6065fdbeb0e5f842732f2dbc2948af3be46dc776
```

**Comment by Alex-Welsh** [comment]
@jovial how tested are these containers?

**Comment by MoteHue** [comment]
> @jovial how tested are these containers?

These are running and working at the client already :)

**Review by MoteHue — APPROVED** [review]
LGTM, @jovial is just double-checking things at the client then he'll merge

**Pull request merged**
