### PR TITLE
Bump RL9 image to RL9.3 (+ 2023.1 tag)

### PR DESCRIPTION
**Pull request by MoteHue**

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Fancy doing an ubuntu one while you're at it?

**Comment by MoteHue** [comment]
> Fancy doing an ubuntu one while you're at it?

Should this wait until the Ubuntu Jammy testing work is completed?

**Comment by Alex-Welsh** [comment]
> > Fancy doing an ubuntu one while you're at it?
> 
> Should this wait until the Ubuntu Jammy testing work is completed?

If you're referring to the upgrades, we're doing them in-place so building a host image for ark would be unrelated

**Review by jovial — APPROVED** [review]
Looks good - I promoted it here: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7814044183/job/21314453693

**Pull request merged**
