### PR TITLE
Yoga: Bump up Ubuntu repo versions

### PR DESCRIPTION
**Pull request by cityofships**
Such change is a great candidate to be automated with periodic workflow.

### CODE REVIEW

**Comment by markgoddard** [comment]
> Such change is a great candidate to be automated with periodic workflow.

Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...

We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)

**Comment by mnasiadka** [comment]
> > Such change is a great candidate to be automated with periodic workflow.
> 
> Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> 
> We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)

I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.

**Comment by markgoddard** [comment]
> > > Such change is a great candidate to be automated with periodic workflow.
> > 
> > 
> > Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> > We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)
> 
> I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.

Ok, but do we now need to rebuild all the containers to match?

**Comment by mnasiadka** [comment]
> > > > Such change is a great candidate to be automated with periodic workflow.
> > > 
> > > 
> > > Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> > > We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)
> > 
> > 
> > I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.
> 
> Ok, but do we now need to rebuild all the containers to match?

match as in one tag for all? well, that's simplicity, right?

**Comment by markgoddard** [comment]
> > > > > Such change is a great candidate to be automated with periodic workflow.
> > > > 
> > > > 
> > > > Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> > > > We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)
> > > 
> > > 
> > > I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.
> > 
> > 
> > Ok, but do we now need to rebuild all the containers to match?
> 
> match as in one tag for all? well, that's simplicity, right?

Match as in having the same packages in the host OS & images.

**Comment by mnasiadka** [comment]
> > > > > > Such change is a great candidate to be automated with periodic workflow.
> > > > > 
> > > > > 
> > > > > Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> > > > > We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)
> > > > 
> > > > 
> > > > I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.
> > > 
> > > 
> > > Ok, but do we now need to rebuild all the containers to match?
> > 
> > 
> > match as in one tag for all? well, that's simplicity, right?
> 
> Match as in having the same packages in the host OS & images.

Does it ever fully match on a production deployment? I doubt that - maybe on day one it does.

**Comment by markgoddard** [comment]
> > > > > > > Such change is a great candidate to be automated with periodic workflow.
> > > > > > 
> > > > > > 
> > > > > > Except for the fact that (on CentOS at least) we typically spend many days doing multinode testing to validate the update...
> > > > > > We've only just added these repo versions for Ubuntu, so probably the changed packages will be quite few, and this should be fairly safe (plus Ubuntu is inherently more stable than stream)
> > > > > 
> > > > > 
> > > > > I think we could be more safe generally with Ubuntu and Rocky 9 automated periodic promotion workflows - and leave the Stream ones as a manual job.
> > > > 
> > > > 
> > > > Ok, but do we now need to rebuild all the containers to match?
> > > 
> > > 
> > > match as in one tag for all? well, that's simplicity, right?
> > 
> > 
> > Match as in having the same packages in the host OS & images.
> 
> Does it ever fully match on a production deployment? I doubt that - maybe on day one it does.

I expect it does mostly currently, because we don't update the repos often

**Review by markgoddard — APPROVED** [review]

**Pull request merged**
