### PR TITLE
Sync stackhpc/2024.1 with stackhpc/2023.1

### PR DESCRIPTION
**Pull request by Alex-Welsh**
The following conflicted in kolla.yml, I've assumed that none of it is required but I'm happy to re-add it if needed:

```yaml
  nova_compute_header:
    # See: https://review.opendev.org/c/openstack/kolla/+/878663/1/docker/neutron/neutron-mlnx-agent/Dockerfile.j2
    RUN sed -e "s/^pyzmq===20.0.0/pyzmq==21.*/g" -i /requirements/upper-constraints.txt
  neutron_server_header:
    # See: https://review.opendev.org/c/openstack/kolla/+/878663/1/docker/neutron/neutron-mlnx-agent/Dockerfile.j2
    RUN sed -e "s/^pyzmq===20.0.0/pyzmq==21.*/g" -i /requirements/upper-constraints.txt
  prometheus_alertmanager_repository_version: | # 2023.1 kolla has 0.24.0
    {% raw %}
    ARG prometheus_alertmanager_version=0.26.0
    ARG prometheus_alertmanager_archive=alertmanager-${prometheus_alertmanager_version}.linux-{{debian_arch}}.tar.gz
    ARG prometheus_alertmanager_sha256sums_url=https://github.com/prometheus/alertmanager/releases/download/v${prometheus_alertmanager_version}/sha256sums.txt
    ARG prometheus_alertmanager_download_url=https://github.com/prometheus/alertmanager/releases/download/v${prometheus_alertmanager_version}/${prometheus_alertmanager_archive}
    {% endraw %}
  prometheus_blackbox_exporter_repository_version: | # 2023.1 kolla has 0.23.0
    {% raw %}
    ARG blackbox_exporter_version=0.25.0
    ARG blackbox_exporter_url=https://github.com/prometheus/blackbox_exporter/releases/download/v${blackbox_exporter_version}/blackbox_exporter-${blackbox_exporter_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
  prometheus_cadvisor_repository_version: | # 2023.1 kolla has 0.48.0
    {% raw %}
    ARG prometheus_cadvisor_version=0.49.1
    {% if debian_arch == 'arm64' %}
    ARG prometheus_cadvisor_sha256sum=c535f46d789599f25c7c680af193d4402da27a98d9828eb2ec916af6256e0c0c
    {% else %}
    ARG prometheus_cadvisor_sha256sum=1d5cc701a3fcdf1e8ed1c86da5304b896a6997d9e6673139e78a6f87812495b0
    {% endif %}
    ARG prometheus_cadvisor_url=https://github.com/google/cadvisor/releases/download/v${prometheus_cadvisor_version}/cadvisor-v${prometheus_cadvisor_version}-linux-{{debian_arch}}
    {% endraw %}
  haproxy_exporter_repository_version: | # 2023.1 kolla has 0.13.0
    {% raw %}
    ARG haproxy_exporter_version=0.15.0
    ARG haproxy_exporter_url=https://github.com/prometheus/haproxy_exporter/releases/download/v${haproxy_exporter_version}/haproxy_exporter-${haproxy_exporter_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
  prometheus_memcached_exporter_repository_version: | #  2023.1 kolla has 0.10.0
    {% raw %}
    ARG memcached_exporter_version=0.14.3
    ARG memcached_exporter_url=https://github.com/prometheus/memcached_exporter/releases/download/v${memcached_exporter_version}/memcached_exporter-${memcached_exporter_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
  prometheus_msteams_repository_version: | # 2023.1 kolla has 1.5.1
    {% raw %}
    ARG prometheus_msteams_version=1.5.2
    ARG prometheus_msteams_sha256sum=0f4df9ee31e655d1ec876ea2c53ab5ae5b07143ef21b9190e61b4d52839e135c
    ARG prometheus_msteams_url=https://github.com/prometheus-msteams/prometheus-msteams/releases/download/v${prometheus_msteams_version}/prometheus-msteams-linux-{{debian_arch}}
    {% endraw %}
  prometheus_mtail_version: | # 2023.1 kolla has 3.0.0-rc50
    {% raw %}
    ARG prometheus_mtail_version=3.0.0-rc53
    ARG prometheus_mtail_url=https://github.com/google/mtail/releases/download/v${prometheus_mtail_version}/mtail_${prometheus_mtail_version}_linux_{{debian_arch}}.tar.gz
    {% endraw %}
  mysqld_exporter_repository_version: | # 2023.1 kolla has 0.15.0
    {% raw %}
    ARG mysqld_exporter_version=0.15.1
    ARG mysqld_exporter_url=https://github.com/prometheus/mysqld_exporter/releases/download/v${mysqld_exporter_version}/mysqld_exporter-${mysqld_exporter_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
  node_exporter_repository_version: | # 2023.1 kolla has 1.4.0
    {% raw %}
    ARG node_exporter_version=1.7.0
    {% if debian_arch == 'arm64' %}
    ARG node_exporter_sha256sum=e386c7b53bc130eaf5e74da28efc6b444857b77df8070537be52678aefd34d96
    {% else %}
    ARG node_exporter_sha256sum=a550cd5c05f760b7934a2d0afad66d2e92e681482f5f57a917465b1fba3b02a6
    {% endif %}
    ARG node_exporter_url=https://github.com/prometheus/node_exporter/releases/download/v{$node_exporter_version}/node_exporter-${node_exporter_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
  prometheus_openstack_exporter_repository_version: | # 2023.1 kolla has 1.6.0
    {% raw %}
    ARG prometheus_openstack_exporter_version=1.7.0
    ARG prometheus_openstack_exporter_url=https://github.com/openstack-exporter/openstack-exporter/releases/download/v${prometheus_openstack_exporter_version}/openstack-exporter_${prometheus_openstack_exporter_version}_linux_{{debian_arch}}.tar.gz
    {% endraw %}
  prometheus_ovn_exporter_repository_version: | # 2023.1 kolla has 1.0.6
    {% raw %}
    {% if base_arch == 'x86_64' %}
    ARG ovn_arch=amd64
    {% elif base_arch == 'aarch64' %}
    ARG ovn_arch=arm64
    {% endif %}
    ARG prometheus_ovn_version=1.0.7
    ARG prometheus_ovn_cksum_url=https://github.com/greenpau/ovn_exporter/releases/download/v${prometheus_ovn_version}/checksums.txt
    ARG ovn_exporter_tgz=ovn-exporter_${prometheus_ovn_version}_linux_${ovn_arch}.tar.gz
    ARG prometheus_ovn_url=https://github.com/greenpau/ovn_exporter/releases/download/v${prometheus_ovn_version}/${ovn_exporter_tgz}
    {% endraw %}
  prometheus_v2_server_repository_version: | # 2023.1 kolla has 2.38.0
    {% raw %}
    ARG prometheus_version=2.51.1
    ARG prometheus_url=https://github.com/prometheus/prometheus/releases/download/v${prometheus_version}/prometheus-${prometheus_version}.linux-{{debian_arch}}.tar.gz
    {% endraw %}
```

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
Upper constraints is borked

**Review by seunghun1ee — APPROVED** [review]

**Review by seunghun1ee — DISMISSED** [review]
Prometheus version override is no longer needed for Caracal.

**Comment by jovial** [comment]
Worth syncing again to pull in the firewall stuff? Otherwise, looks good.

**Comment by Alex-Welsh** [comment]
> Worth syncing again to pull in the firewall stuff?

Done

**Pull request merged**
