### PR TITLE
Rebuild Rocky Linux 9 image with missing packages and newer cloud-init

### PR DESCRIPTION
**Pull request by mnasiadka**
New rocky-container-stackhpc element contains containerfile that installs 'Minimal Install' group which fixes missing packages like microcode_ctl and brings in new cloud-init from c9s that supports NetworkManager and fixes some interface renaming issues.

### CODE REVIEW

**Review by jovial — APPROVED** [review]

**Comment by jovial** [comment]
We did still see the race occurring on at least one node with cloud-init-23.1.1-12.el9.noarch.rpm and the NetworkManager cloud init renderer. I don't think we had the Minimal install group:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    25 |                                                                                                                        | 2023-10-31 14:43 | Install        |    2   
    24 |                                                                                                                        | 2023-10-31 14:43 | Removed        |    2 EE
    23 |                                                                                                                        | 2023-10-31 14:43 | Install        |   19  <
    22 | install tree                                                                                                           | 2023-10-31 14:17 | Install        |    1 > 
    21 |                                                                                                                        | 2023-10-31 14:02 | Install        |    2   
    20 |                                                                                                                        | 2023-10-31 14:02 | Install        |    1 EE
    19 |                                                                                                                        | 2023-10-31 14:02 | Install        |   13 EE
    18 |                                                                                                                        | 2023-10-31 14:01 | Install        |    5   
    17 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
    16 | -v -y install lvm2                                                                                                     | 2023-10-16 11:30 | Install        |    6 EE
    15 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
    14 | -v -y install cryptsetup                                                                                               | 2023-10-16 11:30 | Install        |    1   
    13 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    6   
    12 | -v -y install grub2-tools grub2 efibootmgr grub2-efi-x64 grub2-efi-x64-modules shim-x64                                | 2023-10-16 11:29 | Install        |   47 EE
    11 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |    9   
    10 | -v -y install logrotate net-tools vim git less python3 NetworkManager-config-server linux-firmware cloud-utils-growpar | 2023-10-16 11:29 | Install        |   19 EE
     9 | -v -y remove linux-firmware-whence linux-firmware                                                                      | 2023-10-16 11:29 | Removed        |    2   
     8 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |   26   
     7 | -v -y install dnf-plugins-core python3-libselinux traceroute python3-policycoreutils selinux-policy-targeted tcpdump a | 2023-10-16 11:28 | Install        |  132 EE
     6 | -y update                                                                                                              | 2023-10-16 11:28 | Upgrade        |   16   
     5 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    1   
     4 | -v -y install iscsi-initiator-utils                                                                                    | 2023-10-16 11:28 | Install        |    3 EE
     3 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    2   
     2 | -v -y install gettext python3-PyYAML                                                                                   | 2023-10-16 11:28 | Install        |    2   
     1 | install -y findutils util-linux sudo python3 NetworkManager https://mirror.stream.centos.org/9-stream/AppStream/x86_64 | 2023-10-10 15:59 | I, U           |   77 EE
Failed to store expired repos cache: [Errno 13] Permission denied: '/var/cache/dnf/expired_repos.json'
[stack@compute-12 ~]$ 
```

**Comment by mnasiadka** [comment]
> We did still see the race occurring on at least one node with cloud-init-23.1.1-12.el9.noarch.rpm and the NetworkManager cloud init renderer. I don't think we had the Minimal install group:
> 
> ```
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>     25 |                                                                                                                        | 2023-10-31 14:43 | Install        |    2   
>     24 |                                                                                                                        | 2023-10-31 14:43 | Removed        |    2 EE
>     23 |                                                                                                                        | 2023-10-31 14:43 | Install        |   19  <
>     22 | install tree                                                                                                           | 2023-10-31 14:17 | Install        |    1 > 
>     21 |                                                                                                                        | 2023-10-31 14:02 | Install        |    2   
>     20 |                                                                                                                        | 2023-10-31 14:02 | Install        |    1 EE
>     19 |                                                                                                                        | 2023-10-31 14:02 | Install        |   13 EE
>     18 |                                                                                                                        | 2023-10-31 14:01 | Install        |    5   
>     17 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
>     16 | -v -y install lvm2                                                                                                     | 2023-10-16 11:30 | Install        |    6 EE
>     15 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
>     14 | -v -y install cryptsetup                                                                                               | 2023-10-16 11:30 | Install        |    1   
>     13 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    6   
>     12 | -v -y install grub2-tools grub2 efibootmgr grub2-efi-x64 grub2-efi-x64-modules shim-x64                                | 2023-10-16 11:29 | Install        |   47 EE
>     11 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |    9   
>     10 | -v -y install logrotate net-tools vim git less python3 NetworkManager-config-server linux-firmware cloud-utils-growpar | 2023-10-16 11:29 | Install        |   19 EE
>      9 | -v -y remove linux-firmware-whence linux-firmware                                                                      | 2023-10-16 11:29 | Removed        |    2   
>      8 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |   26   
>      7 | -v -y install dnf-plugins-core python3-libselinux traceroute python3-policycoreutils selinux-policy-targeted tcpdump a | 2023-10-16 11:28 | Install        |  132 EE
>      6 | -y update                                                                                                              | 2023-10-16 11:28 | Upgrade        |   16   
>      5 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    1   
>      4 | -v -y install iscsi-initiator-utils                                                                                    | 2023-10-16 11:28 | Install        |    3 EE
>      3 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    2   
>      2 | -v -y install gettext python3-PyYAML                                                                                   | 2023-10-16 11:28 | Install        |    2   
>      1 | install -y findutils util-linux sudo python3 NetworkManager https://mirror.stream.centos.org/9-stream/AppStream/x86_64 | 2023-10-10 15:59 | I, U           |   77 EE
> Failed to store expired repos cache: [Errno 13] Permission denied: '/var/cache/dnf/expired_repos.json'
> [stack@compute-12 ~]$ 
> ```

Minimal Install basically adds mainly microcode_ctl which adds CPU CVE mitigations (which was missing) - I'm not aware it fixes anything else.

**Comment by jovial** [comment]
> > We did still see the race occurring on at least one node with cloud-init-23.1.1-12.el9.noarch.rpm and the NetworkManager cloud init renderer. I don't think we had the Minimal install group:
> > ```
> > -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> >     25 |                                                                                                                        | 2023-10-31 14:43 | Install        |    2   
> >     24 |                                                                                                                        | 2023-10-31 14:43 | Removed        |    2 EE
> >     23 |                                                                                                                        | 2023-10-31 14:43 | Install        |   19  <
> >     22 | install tree                                                                                                           | 2023-10-31 14:17 | Install        |    1 > 
> >     21 |                                                                                                                        | 2023-10-31 14:02 | Install        |    2   
> >     20 |                                                                                                                        | 2023-10-31 14:02 | Install        |    1 EE
> >     19 |                                                                                                                        | 2023-10-31 14:02 | Install        |   13 EE
> >     18 |                                                                                                                        | 2023-10-31 14:01 | Install        |    5   
> >     17 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
> >     16 | -v -y install lvm2                                                                                                     | 2023-10-16 11:30 | Install        |    6 EE
> >     15 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    1   
> >     14 | -v -y install cryptsetup                                                                                               | 2023-10-16 11:30 | Install        |    1   
> >     13 |                                                                                                                        | 2023-10-16 11:30 | Reason Change  |    6   
> >     12 | -v -y install grub2-tools grub2 efibootmgr grub2-efi-x64 grub2-efi-x64-modules shim-x64                                | 2023-10-16 11:29 | Install        |   47 EE
> >     11 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |    9   
> >     10 | -v -y install logrotate net-tools vim git less python3 NetworkManager-config-server linux-firmware cloud-utils-growpar | 2023-10-16 11:29 | Install        |   19 EE
> >      9 | -v -y remove linux-firmware-whence linux-firmware                                                                      | 2023-10-16 11:29 | Removed        |    2   
> >      8 |                                                                                                                        | 2023-10-16 11:29 | Reason Change  |   26   
> >      7 | -v -y install dnf-plugins-core python3-libselinux traceroute python3-policycoreutils selinux-policy-targeted tcpdump a | 2023-10-16 11:28 | Install        |  132 EE
> >      6 | -y update                                                                                                              | 2023-10-16 11:28 | Upgrade        |   16   
> >      5 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    1   
> >      4 | -v -y install iscsi-initiator-utils                                                                                    | 2023-10-16 11:28 | Install        |    3 EE
> >      3 |                                                                                                                        | 2023-10-16 11:28 | Reason Change  |    2   
> >      2 | -v -y install gettext python3-PyYAML                                                                                   | 2023-10-16 11:28 | Install        |    2   
> >      1 | install -y findutils util-linux sudo python3 NetworkManager https://mirror.stream.centos.org/9-stream/AppStream/x86_64 | 2023-10-10 15:59 | I, U           |   77 EE
> > Failed to store expired repos cache: [Errno 13] Permission denied: '/var/cache/dnf/expired_repos.json'
> > [stack@compute-12 ~]$ 
> > ```
> 
> Minimal Install basically adds mainly microcode_ctl which adds CPU CVE mitigations (which was missing) - I'm not aware it fixes anything else.

We only seemed to hit on one node, so seems much more reliable, but possibly doesn't 100% fix the issue. @Dawud can confirm.

**Comment by dawud** [comment]
Hey @jovial , I think you meant to mention somebody else, not me. Cheers!

**Comment by Alex-Welsh** [comment]
Sorry about that @dawud, I think the intended target was @technowhizz

**Pull request merged**
