### PR TITLE
bump octavia version

### PR DESCRIPTION
**Pull request by scrungus**

### CODE REVIEW

**Comment by mnasiadka** [comment]
Deserves a reno why and what has changed

**Review by mnasiadka — APPROVED** [review]

**Comment by mnasiadka** [comment]
I assume the images have been already promoted, if not - please promote them.

**Comment by scrungus** [comment]
looks like @m-bull has triggered a run

**Comment by scrungus** [comment]
happy to merge?

**Comment by Alex-Welsh** [comment]
> looks like @m-bull has triggered a run

That was for opesearch https://github.com/stackhpc/stackhpc-release-train/actions/runs/5058662587/jobs/9079068711

**Comment by Alex-Welsh** [comment]
Promotion for octavia -> https://github.com/stackhpc/stackhpc-release-train/actions/runs/5058719033/jobs/9079208019

**Comment by Alex-Welsh** [comment]
Promotion succeeded, feel free to merge

**Review by Alex-Welsh — APPROVED** [review]

**Pull request merged**
