### PR TITLE
use ark repos for R9 opensearch builds

### PR DESCRIPTION
**Pull request by bbezak**
also unify opensearch version to 2.11.1

### CODE REVIEW

**Comment by bbezak** [comment]
(let's squash the commits before merge pls)

**Comment by bbezak** [comment]
tested this on yoga/focal - with bump from opensearch 2.9 to 2.11.1 - worked fine

**Review by mnasiadka — APPROVED** [review]

**Review by markgoddard — APPROVED** [review]

**Comment by markgoddard** [comment]
Remember to promote!

**Comment by bbezak** [comment]
done, and tested on focal/yoga@uzh - https://github.com/stackhpc/stackhpc-release-train/actions/runs/7272690430

**Pull request merged**
