### PR TITLE
Bump Ironic image tags

### PR DESCRIPTION
**Pull request by MoteHue**
Draft: to be tested next week

### CODE REVIEW

**Comment by MoteHue** [comment]
Tested and working

**Comment by Alex-Welsh** [comment]
What is this fixing? Also needs a release note

**Comment by seunghun1ee** [comment]
This bump was originally a combination of rebuild for Caracal release and https://github.com/stackhpc/stackhpc-kayobe-config/pull/1341(OSSA-2024-004 fix) but couldn't be tested until now.

**Review by seunghun1ee — DISMISSED** [review]

**Comment by MoteHue** [comment]
> What is this fixing? Also needs a release note

Done

**Review by Alex-Welsh — APPROVED** [review]

**Pull request merged**
