### PR TITLE
Support Rocky Linux 9.4 (Yoga)

### PR DESCRIPTION
**Pull request by m-bull**

### CODE REVIEW

**Review by markgoddard — COMMENTED** [review]
Code change looks sensible. Needs testing in a multinode.

**Comment by Alex-Welsh** [comment]
@m-bull Yoga is already outside of support, and I'm guessing this was tested in prod somewhere. Do you reckon it's reasonable to just get this merged?

**Comment by priteau** [comment]
@m-bull Do we still need this change?

**Comment by m-bull** [comment]
Closed, stale.

**Pull request closed without merging**
