### PR TITLE
Openstack Logs in Grafana

### PR DESCRIPTION
**Pull request by technowhizz**
This PR contains the dashboard that when combined with the right KA patches, should give you logs in the openstack dashboard

### CODE REVIEW

**Comment by markgoddard** [comment]
> WIP

Is it WIP?

**Comment by technowhizz** [comment]
> > WIP
> 
> Is it WIP?

@markgoddard Updated

**Comment by markgoddard** [comment]
> This PR contains the dashboard that when combined with the right KA patches, should give you logs in the openstack dashboard

Do we have these patches in our antelope fork? What would happen in the dashboard if grafana had been deployed without them?

**Comment by technowhizz** [comment]
> > This PR contains the dashboard that when combined with the right KA patches, should give you logs in the openstack dashboard
> 
> Do we have these patches in our antelope fork? What would happen in the dashboard if grafana had been deployed without them?

We just need one more. If it was deployed without them, one would need to manually configure the opensearch datasource inside the grafana UI for the dashboard to work. Wouldn't break any service deploys or the likes.

**Comment by Alex-Welsh** [comment]
@technowhizz Is this ready to go in yet? If not, could you link the changes that still need to merge?

**Comment by dougszumski** [comment]
I tried testing this, but I get an empty panel: 
image

It could be a config error with my env, but I can view logs via the the OpenSearch plugin for Grafana.

This is on master / latest Grafana OSS release. That could also be related.

**Comment by technowhizz** [comment]
This has been fixed now @dougszumski

**Comment by dougszumski** [comment]
This is still blocked on the Kolla upstream commit - we need to be better at chasing these on a regular basis

**Comment by dougszumski** [comment]
The tweak looks good - works for me now. Thanks 

image

**Comment by technowhizz** [comment]
I think this can merge now as we have this patch in our KA https://github.com/stackhpc/kolla-ansible/pull/555

**Review by dougszumski — APPROVED** [review]

**Comment by Alex-Welsh** [comment]
@dougszumski @technowhizz can we still merge this?

**Pull request merged**
