### PR TITLE
Bump Neutron tag to fix multiple bugs

### PR DESCRIPTION
**Pull request by MoteHue**
Building here: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/6826625196

### CODE REVIEW

**Review by jovial — DISMISSED** [review]
Thanks - looks good assuming CI passes.

**Comment by MoteHue** [comment]
PR here to fix builds: https://github.com/stackhpc/stackhpc-kayobe-config/pull/775

**Comment by MoteHue** [comment]
Build running from fixed branch: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/6849523430

**Comment by MoteHue** [comment]
Promotion running here: https://github.com/stackhpc/stackhpc-release-train/actions/runs/6864688479

**Review by markgoddard — APPROVED** [review]

**Pull request merged**
