### PR TITLE
growroot: Fix regex for md (sw-raid) cases

### PR DESCRIPTION
**Pull request by mnasiadka**

### CODE REVIEW

**Review by grzegorzkoper — APPROVED** [review]
LGTM +1
Tested in SMSLAB

**Comment by markgoddard** [comment]
How does it relate to #818?

**Comment by mnasiadka** [comment]
> How does it relate to #818?

It doesn't, I haven't seen it - and given the endless thread in there and no resolution - maybe we can merge something that is not ideal but still helpful?

**Comment by markgoddard** [comment]
> > How does it relate to #818?
> 
> It doesn't, I haven't seen it - and given the endless thread in there and no resolution - maybe we can merge something that is not ideal but still helpful?

The issue is that there's scope for regression, and other related issues.

**Comment by mnasiadka** [comment]
> > > How does it relate to #818?
> > 
> > 
> > It doesn't, I haven't seen it - and given the endless thread in there and no resolution - maybe we can merge something that is not ideal but still helpful?
> 
> The issue is that there's scope for regression, and other related issues.

Let's go with #818, I tested it on all three possible disk names.

**Pull request closed without merging**
