### PR TITLE
Reduce ESP partition size in deployment image

### PR DESCRIPTION
**Pull request by cityofships**
It does not fit into 550MiB partition created by Ironic Python Agent. This is relevant when provisioning software RAID UEFI enabled servers.

https://github.com/openstack/ironic-python-agent/blob/stable/yoga/ironic_python_agent/raid_utils.py#L30

### CODE REVIEW

**Review by mnasiadka — DISMISSED** [review]

**Comment by markgoddard** [comment]
Do we need new host images with this change included?

**Comment by cityofships** [comment]
> Do we need new host images with this change included?

Yes. Before that's available, one can either virt-customize local image or use IPA with `ESP_SIZE_MIB` modified to something bigger.

**Comment by cityofships** [comment]
Building in: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/6495483910

**Comment by priteau** [comment]
Is this an upstream issue too? DIB defaults to 550 MiB and IPA too, but the DIB image doesn't fit into what IPA creates? Maybe IPA should be just slightly bigger?

**Comment by mnasiadka** [comment]
> Is this an upstream issue too? DIB defaults to 550 MiB and IPA too, but the DIB image doesn't fit into what IPA creates? Maybe IPA should be just slightly bigger?

I think it's rather the issue of our layout that we pass to DIB?

**Review by mnasiadka — APPROVED** [review]

**Comment by mnasiadka** [comment]
I'll rebuild the images as part of https://github.com/stackhpc/stackhpc-kayobe-config/pull/721

**Comment by cityofships** [comment]
> > Is this an upstream issue too? DIB defaults to 550 MiB and IPA too, but the DIB image doesn't fit into what IPA creates? Maybe IPA should be just slightly bigger?
> 
> I think it's rather the issue of our layout that we pass to DIB?

It's probably rounding / calculations error, I saw the ESP partition 0,1MB too big for MD created by IPA. It's easier to change here than a hard-coded value in IPA for us.

**Comment by mnasiadka** [comment]
Merging as this is not tested in aio

**Pull request merged**
