### PR TITLE
Stop deploying Docker registry

### PR DESCRIPTION
**Pull request by cityofships**
We don't use this one, do we?

### CODE REVIEW

**Review by priteau — APPROVED** [review]

**Comment by Alex-Welsh** [comment]
The comment says default is false. If that's true why do we need to set the var?

**Comment by cityofships** [comment]
> The comment says default is false. If that's true why do we need to set the var?

Comment inaccurate? https://github.com/stackhpc/kayobe/blob/stackhpc/2023.1/ansible/roles/docker-registry/defaults/main.yml#L9

Perhaps there was a higher precedence variable that got removed at some point?

**Comment by MoteHue** [comment]
> > The comment says default is false. If that's true why do we need to set the var?
> 
> Comment inaccurate? https://github.com/stackhpc/kayobe/blob/stackhpc/2023.1/ansible/roles/docker-registry/defaults/main.yml#L9
> 
> Perhaps there was a higher precedence variable that got removed at some point?

It's overridden in Kayobe group vars: https://github.com/stackhpc/kayobe/blob/54b9e92f5e1e5fc9ea026cee682f9ce1ce0ea794/ansible/inventory/group_vars/all/docker-registry#L6

**Comment by cityofships** [comment]
> > > The comment says default is false. If that's true why do we need to set the var?
> > 
> > 
> > Comment inaccurate? https://github.com/stackhpc/kayobe/blob/stackhpc/2023.1/ansible/roles/docker-registry/defaults/main.yml#L9
> > Perhaps there was a higher precedence variable that got removed at some point?
> 
> It's overridden in Kayobe group vars: https://github.com/stackhpc/kayobe/blob/54b9e92f5e1e5fc9ea026cee682f9ce1ce0ea794/ansible/inventory/group_vars/all/docker-registry#L6

Yet the task has been firing anyway: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7574482605/job/20628969896#step:7:976

**Comment by markgoddard** [comment]
> > > > The comment says default is false. If that's true why do we need to set the var?
> > > 
> > > 
> > > Comment inaccurate? https://github.com/stackhpc/kayobe/blob/stackhpc/2023.1/ansible/roles/docker-registry/defaults/main.yml#L9
> > > Perhaps there was a higher precedence variable that got removed at some point?
> > 
> > 
> > It's overridden in Kayobe group vars: https://github.com/stackhpc/kayobe/blob/54b9e92f5e1e5fc9ea026cee682f9ce1ce0ea794/ansible/inventory/group_vars/all/docker-registry#L6
> 
> Yet the task has been firing anyway: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/7574482605/job/20628969896#step:7:976

The role asserts that the service is not running rather than skipping it - that's why it shows as unchanged

**Pull request merged**
